---
- hosts: localhost
  become: yes
  tasks:
    - name: Update apt and autoremove
      apt:
        upgrade: 'yes'
        update_cache: 'yes'
        autoremove: 'yes'

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt and autoremove
      apt:
        update_cache: 'yes'

    - name: Install Docker
      apt: name={{ item }} state=latest
      loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']

    - name: Ensure Docker service is running
      systemd:
        state: started
        enabled: yes
        name: docker

    - name: Add the user to the docker group
      user:
        name: "{{ ansible_env.USER }}"
        group: docker
        append: yes
