---
- hosts: localhost
  become: yes
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes

  - name: Install software-properties-common
    apt:
      name: software-properties-common
      state: present

  - name: Add Microsoft repository key for VSCode
    apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

  - name: Add Microsoft repository for VSCode
    apt_repository:
        repo: deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/vscode stable main
        state: present

  - name: Install Visual Studio Code
    apt:
        name: code
        state: present


  - name: get SublimeText repo key
    get_url:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      dest: /tmp/sublimetext_gpg
      mode: ugo+rw


  - name: De-Armor SublimeText repo's GPG key
    expect:
        command:  gpg --output /etc/apt/trusted.gpg.d/sublimehq-archive.gpg --dearmor /tmp/sublimetext_gpg 
        responses:
            '(y/N)': y


  - name: add SublimeText repository
    apt_repository:
      repo: "deb [arch=amd64, signed-by=/etc/apt/trusted.gpg.d/sublimehq-archive.gpg] https://download.sublimetext.com apt/stable/"
      state: present
      filename: sublime_text_repo
      update_cache: yes
      mode: 0644
      validate_certs: no


  - name: Install Sublime Text
    apt:
      name: sublime-text
      state: present


