---
- hosts: localhost
  become: yes
  vars:
    vim_user: your_username  # Replace with your username
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install Vim
      apt:
        name: vim
        state: present

    - name: Install ctags and cscope for tag navigation
      apt:
        name:
          - exuberant-ctags
          - cscope
        state: present

    - name: Install Git
      apt:
        name: git
        state: present



    - name: Install useful tools
      apt:
        name:
          - terminator
          - build-dep python-psycopg2
          - dos2unix
          - tldr
          - xclip
          - pinta
          - poppler-utils
          - sublime-text
          - flameshot
          - curl
          - nodejs
          - npm
          - python3.10-venv
        state: present


    - name: Install zsh
      apt:
        name: zsh
        state: present

    - name: Make zsh the default shell
      command: chsh -s /bin/zsh {{ ansible_user }}
      args:
        warn: no
      become_user: "{{ ansible_user }}"
      when: ansible_facts['shell'] != "/bin/zsh"

    - name: Install Oh-My-Zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "~/.oh-my-zsh"
      become_user: "{{ ansible_user }}"
    
    - name: Install popular plugins (example)
      git:
        repo: "https://github.com/{{ item.plugin_repo }}"
        dest: "~/.oh-my-zsh/custom/plugins/{{ item.plugin_name }}"
        depth: 1
      loop:
        - { plugin_name: 'zsh-autosuggestions', plugin_repo: 'zsh-users/zsh-autosuggestions' }
        - { plugin_name: 'zsh-syntax-highlighting', plugin_repo: 'zsh-users/zsh-syntax-highlighting' }
      become_user: "{{ ansible_user }}"

    - name: Update .zshrc to load plugins
      lineinfile:
        path: "~/.zshrc"
        backrefs: yes
        regexp: '^plugins=\((.*)\)$'
        line: 'plugins=(\1 zsh-autosuggestions zsh-syntax-highlighting)'
      become_user: "{{ ansible_user }}"
     

    - name: Install Vundle (Vim package manager)
      become: no
      git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: "~{{ vim_user }}/.vim/bundle/Vundle.vim"
        version: master
        accept_hostkey: yes

    - name: Configure .vimrc file
      become: no
      blockinfile:
        path: "~{{ vim_user }}/.vimrc"
        create: yes
        block: |
          set nocompatible
          filetype off
          set rtp+=~/.vim/bundle/Vundle.vim
          call vundle#begin()

          Plugin 'VundleVim/Vundle.vim'

          " Add all your plugins here
          Plugin 'preservim/nerdtree'          " File explorer
          Plugin 'Xuyuanp/nerdtree-git-plugin' " Git integration for NERDTree
          Plugin 'airblade/vim-gitgutter'      " Git integration
          Plugin 'preservim/nerdcommenter'     " For easy code commenting
          Plugin 'jiangmiao/auto-pairs'        " For pairing brackets, quotes, etc.
          Plugin 'scrooloose/syntastic'        " Syntax checking
          Plugin 'vim-airline/vim-airline'     " Status bar
          Plugin 'vim-airline/vim-airline-themes' " Themes for status bar
          Plugin 'itchyny/lightline.vim'       " Lightweight status line
          Plugin 'vim-scripts/taglist.vim'     " Source code browser (requires ctags)

          call vundle#end()
          filetype plugin indent on

          " Further custom vimrc configurations can go here

    - name: Install Vim plugins
      become: no
      shell: vim +PluginInstall +qall
      args:
        executable: /bin/bash
